name: Test

on:
  [pull_request,push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v4
      - name: "setup pnpm"
        uses: "pnpm/action-setup@v4"
      - name: "setup node"

        uses: "actions/setup-node@v4"
        with:
          node-version: 20
      - name: Install and Build
        run: pnpm install && pnpm run build
